language: node_js
sudo: required
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DOCKER_HOST="$HOST_NAME"
script:
- docker build -t $DOCKER_USERNAME/htmltest .
- docker push $DOCKER_USERNAME/htmltest
after_success:
- docker stop htmltest
- docker rm htmltest
- docker run -p 8088:80 -d --name htmltest $DOCKER_USERNAME/htmltest:latest
service: docker

env:
  global:
  - secure: I7q6azTWtUej0YCWzLlS6NV1nRL22/xqHjRZzhTjAiZwvGWnXuIC/bQ+2z46R3qBRWyFuFiY5NAfNLDAEa/IZkQVs0i9UjxXb0GgR3DyXdNHQz9uE0ie0qyFrei3Mg1iJLH7ZIiDv0UVGXGBw3H7cTqAfhEcq4DDJqhtmN95vh+k5F+pApa8GKOSFXzmgXonoXzADPGaKx2Br6QKv9U/g+E4W0tMWOrR1YqoDJYcBchbB2YfgHJ6BnB342Pj3RNbOSDrQxM0/mh/XmcT6JlzUj04xg3OLTksVj3CW9ERWYecA4IZjZ+D/2UfZxVwtOMfh2v+8vj0CzcB/Rz6rhirprNhDBmu6/VN+VEXigKWFXkSQgzoIaVh1NhxssFmWaSggRxJhBuIhl2KCATZMBx3I3B4ELrlUziFAiMaN1kh1immm4RNRF6fcQt3U9Z1Ex+822y0eMb1hVhPNT+HZFX9/opuECn/kz6a1RX8Psnd5ena0XNVLOzQgaj9NYVnFVfIagY9+WvJJqlRFeZuWnX8BEOn1q41MQrlaq5A02cdxwZF5myxWdf+x3rtcNe2/Abg+adpqzjXDLi35tsfH5ySQ4KZU7dwNgho7Sa/WvH+3CNFwOQOVpf2N5ILs07ihH6SNruIFRESh35yzmWOX8pXjUYdfdhmq3bVPxuMWZzRrsg=
  - secure: NjkfiB/HPh0CROJuSLK+4ARjXQRt4h3R1pyujVSFs7kc6/jmUizSqHgtcaUOYPzxdgtbMMTtsAyLSukpNrSc5Lte6KjbqkEUj7UR1MlJ/YrWec+qrb1VEtdmXDwR0FTOCAmnJe6BXbC34ehyOqFkeZliFgr2f5iAp/o6BEfNd23qqKIMbL+yirulSyPa0V3KBFTJ5XpOB1C9xV+cfzJzDZQm7BunKwJLthqf2A2cxJjQg9uQsiesoKfVROk9KUW/KjSJeGmGxovBd8jK9t6u5bPwauRfGQWxhirlDzt1Airm7aO8SgZ6+RB+FPpqY9OGUmSEg1rpPPwZ36+aFwFINrjwSY8M3peeOKc2W6GUlF03GMDSNMGAQEHvrFgBq7H/94XhcDdJpTaMyotoFfyxek5SolwuOV+dTRwmTnGhlhsccIfYWoXDeShOHnMd3/EXtJEky0mcyXnx1WAvGuu0LyRTpso+cZeDUOKR39MeA1J1+XOFtuCUi8mssJJk5HG4TwzetvBn0v4i3eYzDHdT0iMDYES5315UMeBick3tk9d6NjL1a3GpNAkLMwXN3Fq028EiyNqzXcORvsrtHDcQoZMcc0umvw6MhyqpNTfhljNwKtMN/Q3UbizRm2vC80cUeKrmWRIAopPm+FNLkHG+anvcpqflybyf64IhtAbC/88=
  - secure: N3WrTWWXuH4GSFZNciKdDiLExDYuoVAKC5H+2KMO/8dxNDxDxUS1Q1uB2FgWjBnTDc27u6T76fb83zCL4g6x4hrjZfHOmc8uZpBcUcT8ZC50P/BBwyDny0hLnP/UJxVlcA617Pp4lwqUaqVsBzOz2TKfSoixUGuNj52i5jD5wWzCOrMh0l5bqttASJfAy0LUu77ln1lQo278vYgERECUYM/KuJKFhao/Cmkdp98RPfeF00BDpRNaQmk/hbtoagErpPy3EwuPIo65t/BaQW6+kmOixRJyoXZIPgq1BYW5b5SVH4rvLuJtMnEX+sC6JL7jJuSrm3Zf62NBx8cBHFUvNwZISjlKNLFaZIo/3iTj4dzW4sy/Uum1dn5OihRwO3sjmG5IMfAquRIobL/Zr4UJRT0XC6kXz3Ip3Y8jfQf0ZD31qv9uQ5KtFWDqft8TqS1EN7GapOLSn0HWRRdnBPVV1M1GCi335KJwIRJnjs8K6WOQsr6wuEz0J7HtfEsf+5m9bC3L6SrG8xVnWlwFUE4MrDKakSV1VWfiFrlqo+RdDjRrEGHO6pG0t5kDhd319Esd+q5phAFcMnQ8/UHcSQQgA+EfaAfgdPW4tUyUx7StPSlfpCM9vny7WLHDSZ5w1T6W9DJYPZ0vOurzHklVeQnsql5Xxv+nsRldVH7CyLpcO8M=
